import "./globals.css";

import Header from "./components/main/header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: { url: "@/asset/logo3.png", type: "image/x-icon" },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Header />
        <main className="mt-20">
          <div className="m-10 rounded-xl bg-[#EEEEEE] min-h-9/10">
            {children}
          </div>
        </main>
        
        <footer className="bg-black text-white">
          <div>|</div>
          <div>Michał Dańko</div>
          <div>|</div>
          <div>Artur Grodel</div>
          <div>|</div>
          <div>Filip Kłos</div>
          <div>|</div>
          <div>Andrzej Posim</div>
          <div>|</div>
        </footer>
        
      </body>
    </html>
  );
}
